apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: quote-service-rt
  name: quote-service-rt
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: quote-service-rt
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: quote-service-rt
    spec:
      containers:
      - image: gcr.io/pgtm-gwestenberg/quote-service-rt:latest
        imagePullPolicy: Always
        name: quote-service
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30