apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: quote-service-db
  name: quote-service-db
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: quote-service-db
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: quote-service-db
    spec:
      containers:
      - image: gcr.io/pgtm-gwestenberg/quote-service-db:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: postgres-secret
          mountPath: /etc/postgres-secret
          readOnly: true
        name: quote-service
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: POSTGRES_HOST
          value: "postgres-postgresql"
        - name: POSTGRES_PORT
          value: "5432"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: postgres-secret
        secret:
          secretName: postgres-secret
          items:
          - key: username
            path: username
          - key: password
            path: password
