apiVersion: v1
kind: Service
metadata:
  labels:
    run: quote-service
  name: quote-service
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: quote-service
  sessionAffinity: None
  type: LoadBalancer
