apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    run: quote-service
  name: quote-service
  namespace: default
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/quote-service
spec:
  replicas: 1
  selector:
    matchLabels:
      run: quote-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: quote-service
    spec:
      containers:
      - image: jaredgordon/quote-service:2.0.2
        imagePullPolicy: Always
        volumeMounts:
        - name: postgres-secret
          mountPath: /etc/postgres-secret
          readOnly: true
        name: quote-service
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: postgres-secret
        secret:
          secretName: postgres-secret
          items:
          - key: username
            path: username
          - key: password
            path: password
