---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: '3.3.9-jdk-8-onbuild'

inputs:
- name: quote-tile-repo
  path: /usr/src/app

outputs:
- name: quote-tile
  path: /usr/src/app/target

run:
  path: /usr/share/mvn
#  args:
#  - package
#  - -e

#run:
#  path: /usr/src/app/ci/scripts/tile-build.sh
#  args:
 # - usr/src/app/target
#  - -e